channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.14.0
  - cloudpickle==3.1.2
  - dill==0.3.8
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.1.4
  - pyyaml==6.0.1
  - torch==2.9.1
  - tqdm==4.67.1
name: mlflow-env
